seed: 42

resources:
  dir: resources

machine:
  device: cpu
  num_workers: 6

data:
  fiftyone:
    download_dir: None

dev:
  single_image: resources/sample_images/Places365_test_00000001.jpg
  temp_outout_dir: temp_output