seed: 42

resources:
  dir: resources

machine:
  device: cpu
  num_workers: 6

data:
  fiftyone:
    download_dir: None
  tar:
    places365_validation:
      url: "http://data.csail.mit.edu/places/places365/val_large.tar"
      download_dir: None


dev:
  single_image: resources/sample_images/Places365_test_00000001.jpg
  temp_output_dir: temp_output
  cloned_image_dir: resources/cloned_images

image_acquisition:
  places365_val_large:
    type: tar
    source_url: "https://data.csail.mit.edu/places/places365/val_large.tar"
    destination_dir: places365
    extracted_root: val_large
    target_hash: 2bc267e86fccdb40e1b53dda2084b61d160cca6ccdb571e817ce451cbebf9b75
  div2k_valid_hr:
    type: zip
    source_url: "https://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_HR.zip"
    destination_dir: div2k
    extracted_root: hr/validation/DIV2K_valid_HR
    target_hash: 6e15600592955c5117a29181f0d46f7b43cd3f11bc94453ca7929f6fedd9aec7
  single_image:
    type: local_resource
    resource_file_path: div2k_single_image.tar
    destination_dir: div2k_single_image
    extracted_root: single_image
    target_hash: 25b79978f6fa9c5764f680ac4d0f5dfea0edda6fe7eeefd9e4777b846eda9966
  five_images:
    type: local_resource
    resource_file_path: div2k_five_images.tar
    destination_dir: div2k_five_images
    extracted_root: five_images
    target_hash: bb3b48c46e74a2975813070093565efb75b94dd38f17572a45d3b7b45aeccbe7
  twenty_images:
    type: local_resource
    resource_file_path: div2k_twenty_images.tar
    destination_dir: div2k_twenty_images
    extracted_root: twenty_images
    target_hash: 57ebbdabe97cb371197cd0dc267374b08e0c5d8048044f93570388ddc19b8bb8


